export const SET_SINGER = 'SET_SINGER'
export const GET_SLIDER = 'GET_SLIDER'
export const NORMALIZE_SINGERS = 'NORMALIZE_SINGERS'
export const SORT_SINGERS = 'SORT_SINGERS'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'